/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.EmpProfile;
import model.EmpProfilesData;

/**
 *
 * @author mohit
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    
    EmpProfilesData data; 
    
    String name;
    String empId;
    int age;
    String gender;
    Date startDate;
    int level;
    String teamInfo;
    String phoneNo;
    String positionTitle;
    String emailAddress;
    
    public CreateJPanel(EmpProfilesData data) {
        initComponents();
        
        this.data = data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtEmpId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        txtLevel = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        lblHeading = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmpId = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        btnAddEmp = new javax.swing.JButton();
        btnPhoto = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblImageLoc = new javax.swing.JLabel();

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblHeading.setText("Enter New Employee Details");

        lblName.setText("Name:");

        lblEmpId.setText("Employee ID:");

        lblAge.setText("Age:");

        lblGender.setText("Gender:");

        lblStartDate.setText("Start Date:");

        lblLevel.setText("Level:");

        lblTeamInfo.setText("Team Info: ");

        lblPositionTitle.setText("Position Title:");

        lblPhoneNo.setText("Cell Phone No:");

        lblEmailAddress.setText("Email Address:");

        lblPhoto.setText("Photo:");

        btnAddEmp.setText("Add Employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });

        btnPhoto.setText("Upload");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImageLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(lblHeading))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmpId)
                                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblStartDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLevel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(lblTeamInfo)
                                        .addComponent(lblPositionTitle)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmailAddress)
                                    .addComponent(lblPhoneNo))
                                .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(94, 94, 94)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(txtEmpId)
                                .addComponent(txtLevel)
                                .addComponent(txtTeamInfo)
                                .addComponent(txtPositionTitle)
                                .addComponent(txtEmailAddress)
                                .addComponent(txtPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                .addComponent(txtAge)
                                .addComponent(txtGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(301, 301, 301)
                            .addComponent(btnPhoto)
                            .addGap(62, 62, 62)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(btnAddEmp))))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblHeading)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpId)
                    .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStartDate)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLevel)
                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTeamInfo)
                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPositionTitle)
                    .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNo)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmailAddress)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhoto)
                        .addComponent(btnPhoto))
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblImageLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAddEmp)
                .addContainerGap(306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
        try{
            name = txtName.getText();
            empId = txtEmpId.getText();
            age = Integer.parseInt(txtAge.getText());
            gender = txtGender.getText();
            startDate = jDateChooser.getDate();
            level = Integer.parseInt(txtLevel.getText());
            teamInfo = txtTeamInfo.getText();
            phoneNo = txtPhoneNo.getText();
            positionTitle = txtPositionTitle.getText();
            emailAddress = txtEmailAddress.getText();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Please enter all values and try again");
        }
        
        if(isValidInput()){
            EmpProfile ep = data.addNewProfile();

            ep.setName(name);
            ep.setEmpId(empId);
            ep.setAge(age);
            ep.setGender(gender);
            ep.setStartDate(startDate);
            ep.setLevel(level);
            ep.setTeamInfo(teamInfo);
            ep.setPhoneNo(phoneNo);
            ep.setPositionTitle(positionTitle);
            ep.setEmailAddress(emailAddress);
            ep.setPhoto(lblImageLoc.getText());

            JOptionPane.showMessageDialog(this, "Employee details saved successfully");

            txtName.setText("");
            txtEmpId.setText("");
            txtAge.setText("");
            txtGender.setText("");
            jDateChooser.setDate(null);
            txtLevel.setText("");
            txtTeamInfo.setText("");
            txtPhoneNo.setText("");
            txtPositionTitle.setText("");
            txtEmailAddress.setText("");
            lblImageLoc.setText("");
            lblImage.setIcon(new ImageIcon());
        }
    }//GEN-LAST:event_btnAddEmpActionPerformed
    
    private boolean isValidInput(){
        ArrayList message = null;
        message = new ArrayList(0);
        if (name.isBlank() || !(name.matches("^[a-zA-Z]*$"))){
            message.add("Name cannot be blank, contain digits or special characters. Please enter a valid name and try again");
        }

        if(empId.isBlank() || !(empId.matches("^[a-zA-Z1-9_-]*$"))){
            message.add("Please enter a valid alphanumeric Employee ID and try again");
        }
        
        if(age < 17 || age > 99){
            message.add("Please enter a valid Age (18-99) and try again");
        }
        
        if(gender!= null && (!(gender.equalsIgnoreCase("Male")|| gender.equalsIgnoreCase("Female")|| gender.equalsIgnoreCase("Other")))){
        message.add("Please enter a valid Gender (Male/Female/Other) and try again");
        }

        if(!(String.valueOf(phoneNo).matches("[0-9]{10}$"))){
            message.add("Please enter a valid 10 digit Phone No and try again");
        }
        
        if(level<1 || level>15){
            message.add("Please enter a valid Level (1-15) and try again");
        }

        if(teamInfo != null && (teamInfo.isBlank() || !(teamInfo.matches("^[ a-zA-Z1-9_-]*$")))){
            message.add("Please enter a valid alphanumeric Team Info and try again");
        }

         if(emailAddress!= null && (emailAddress.isBlank() || !(emailAddress.matches("^[A-Za-z0-9+_.-]+@(.+)$")) || !(emailAddress.contains("@"))||!(emailAddress.endsWith(".com")))){
            message.add("Please enter a valid Email Address and try again");
        }

        if(!(message.isEmpty())){
            JOptionPane.showMessageDialog(this, message.toArray());
            message.clear();
            return false;
        }
        else{
                return true;
            }
        }
    
    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
    
        FileNameExtensionFilter extFilter = new FileNameExtensionFilter("IMAGES", "jpeg", "png" ); 
    
        int showOpenDialog = chooser.showOpenDialog(null); 
        
        chooser.addChoosableFileFilter(extFilter);
        if(showOpenDialog == JFileChooser.APPROVE_OPTION){
            File selectedImage =  chooser.getSelectedFile();
            String selectedImagePath = selectedImage.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            
            lblImageLoc.setText(selectedImagePath);
            
            ImageIcon icon = new ImageIcon(selectedImagePath);
            Image image = icon.getImage().getScaledInstance(lblImage.getHeight(), lblImage.getWidth(), Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btnPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnPhoto;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImageLoc;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
