/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;
import model.House;
import model.HouseDirectory;

/**
 *
 * @author mohit
 */
public class CommunityAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityAdminJPanel
     */
    JSplitPane sp;
    CityDirectory cd;
    CommunityDirectory comd;
    HouseDirectory hod;
    
    String cityName;
    
    String commName;
    String commCity;
    
    String houseName;
    String houseComm;
    String houseCity;
    
    public CommunityAdminJPanel(JSplitPane sp, CityDirectory cd, CommunityDirectory comd, HouseDirectory hod) {
        initComponents();
        
        this.sp = sp;
        this.cd = cd;
        this.comd = comd;
        this.hod = hod;
        
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewCities = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCities = new javax.swing.JTable();
        btnViewUpdateCity = new javax.swing.JButton();
        lblCityName = new javax.swing.JLabel();
        txtCityName = new javax.swing.JTextField();
        btnCreatePatient = new javax.swing.JButton();
        btnAddCity = new javax.swing.JButton();
        btnUpdateCity = new javax.swing.JButton();
        btnCreateCommunity = new javax.swing.JButton();
        btnAddCommunity = new javax.swing.JButton();
        btnViewCommunities = new javax.swing.JButton();
        btnUpdateCommunity = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCommunities = new javax.swing.JTable();
        btnViewUpdateCommunity = new javax.swing.JButton();
        lblCommunityName = new javax.swing.JLabel();
        txtCommunityName = new javax.swing.JTextField();
        lblCommunityCity = new javax.swing.JLabel();
        txtCommunityCity = new javax.swing.JTextField();
        btnUpdateHouse = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHouses = new javax.swing.JTable();
        btnViewUpdateHouse = new javax.swing.JButton();
        lblHouseName = new javax.swing.JLabel();
        txtHouseName = new javax.swing.JTextField();
        lblHouseCommunity = new javax.swing.JLabel();
        txtHouseCommunity = new javax.swing.JTextField();
        btnCreateHouse = new javax.swing.JButton();
        btnAddHouse = new javax.swing.JButton();
        btnViewHouses = new javax.swing.JButton();
        lblHouseCity = new javax.swing.JLabel();
        txtHouseCity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewCities.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnViewCities.setText("View Cities");
        btnViewCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCitiesActionPerformed(evt);
            }
        });
        add(btnViewCities, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 29, -1, -1));

        tblCities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(tblCities);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 270, 100));

        btnViewUpdateCity.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnViewUpdateCity.setText("View/Update Details");
        btnViewUpdateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateCityActionPerformed(evt);
            }
        });
        add(btnViewUpdateCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 182, -1, -1));

        lblCityName.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblCityName.setText("Name:");
        add(lblCityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 244, -1, -1));

        txtCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityNameActionPerformed(evt);
            }
        });
        add(txtCityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 241, 187, -1));

        btnCreatePatient.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnCreatePatient.setText("Create New City");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });
        add(btnCreatePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 29, -1, -1));

        btnAddCity.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnAddCity.setText("Add City");
        btnAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCityActionPerformed(evt);
            }
        });
        add(btnAddCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        btnUpdateCity.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnUpdateCity.setText("Update City");
        btnUpdateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCityActionPerformed(evt);
            }
        });
        add(btnUpdateCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        btnCreateCommunity.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnCreateCommunity.setText("Create New Community");
        btnCreateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommunityActionPerformed(evt);
            }
        });
        add(btnCreateCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        btnAddCommunity.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnAddCommunity.setText("Add Community");
        btnAddCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommunityActionPerformed(evt);
            }
        });
        add(btnAddCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        btnViewCommunities.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnViewCommunities.setText("View Communities");
        btnViewCommunities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCommunitiesActionPerformed(evt);
            }
        });
        add(btnViewCommunities, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        btnUpdateCommunity.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnUpdateCommunity.setText("Update Community");
        btnUpdateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCommunityActionPerformed(evt);
            }
        });
        add(btnUpdateCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        tblCommunities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane2.setViewportView(tblCommunities);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 360, 100));

        btnViewUpdateCommunity.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnViewUpdateCommunity.setText("View/Update Details");
        btnViewUpdateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateCommunityActionPerformed(evt);
            }
        });
        add(btnViewUpdateCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        lblCommunityName.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblCommunityName.setText("Name:");
        add(lblCommunityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        txtCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityNameActionPerformed(evt);
            }
        });
        add(txtCommunityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 187, -1));

        lblCommunityCity.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblCommunityCity.setText("City:");
        add(lblCommunityCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        txtCommunityCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityCityActionPerformed(evt);
            }
        });
        add(txtCommunityCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 187, -1));

        btnUpdateHouse.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnUpdateHouse.setText("Update House");
        btnUpdateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHouseActionPerformed(evt);
            }
        });
        add(btnUpdateHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, -1, -1));

        tblHouses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane3.setViewportView(tblHouses);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 70, 312, 100));

        btnViewUpdateHouse.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnViewUpdateHouse.setText("View/Update Details");
        btnViewUpdateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateHouseActionPerformed(evt);
            }
        });
        add(btnViewUpdateHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 182, -1, -1));

        lblHouseName.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblHouseName.setText("Name:");
        add(lblHouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 232, -1, -1));

        txtHouseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseNameActionPerformed(evt);
            }
        });
        add(txtHouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 229, 187, -1));

        lblHouseCommunity.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblHouseCommunity.setText("Community:");
        add(lblHouseCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 273, -1, -1));

        txtHouseCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseCommunityActionPerformed(evt);
            }
        });
        add(txtHouseCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 270, 187, -1));

        btnCreateHouse.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnCreateHouse.setText("Create New House");
        btnCreateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHouseActionPerformed(evt);
            }
        });
        add(btnCreateHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

        btnAddHouse.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnAddHouse.setText("Add House");
        btnAddHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHouseActionPerformed(evt);
            }
        });
        add(btnAddHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));

        btnViewHouses.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btnViewHouses.setText("View Houses");
        btnViewHouses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHousesActionPerformed(evt);
            }
        });
        add(btnViewHouses, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 29, -1, -1));

        lblHouseCity.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblHouseCity.setText("City:");
        add(lblHouseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 314, -1, -1));

        txtHouseCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseCityActionPerformed(evt);
            }
        });
        add(txtHouseCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 311, 187, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mohit/Desktop/INFO5100 (14259) Application Engineering and Development /Rayalacheruvu_Maruti_002109594/Assignment2_HospitalCRUD/images/home.png")); // NOI18N
        jLabel1.setText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 1010));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCitiesActionPerformed
        // TODO add your handling code here:
        populateCities();
    }//GEN-LAST:event_btnViewCitiesActionPerformed

    private void btnViewUpdateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateCityActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCities.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a person to view their details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCities.getModel();
        City c= (City) model.getValueAt(selectedRowIndex, 0);

        //        Patient p = pd.getPatient(selectedPatient);
        lblCityName.setVisible(true);
        txtCityName.setVisible(true);
        btnUpdateCity.setVisible(true);

        txtCityName.setText(c.getName());
        
        
    }//GEN-LAST:event_btnViewUpdateCityActionPerformed

    private void txtCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityNameActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        lblCityName.setVisible(true);
        txtCityName.setVisible(true);
        btnAddCity.setVisible(true);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCityActionPerformed
        // TODO add your handling code here:
        try{
            cityName = txtCityName.getText();
            if(cityValidation()){
                City c = cd.addNewCity();
                c.setName(cityName);
                initialSetup();
                JOptionPane.showMessageDialog(this, "City added");
                populateCities();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter all values and try again");
        }
    }//GEN-LAST:event_btnAddCityActionPerformed

    private void btnUpdateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCityActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCities.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a city to view its details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCities.getModel();
        City c= (City) model.getValueAt(selectedRowIndex, 0);
        try{
            cityName = txtCityName.getText();
            if(cityValidation()){
                c.setName(cityName);
                initialSetup();
                JOptionPane.showMessageDialog(this, "City updated");
                populateCities();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter all values and try again");
        }
    }//GEN-LAST:event_btnUpdateCityActionPerformed

    private void btnCreateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommunityActionPerformed
        // TODO add your handling code here:
        lblCommunityName.setVisible(true);
        txtCommunityName.setVisible(true);
        lblCommunityCity.setVisible(true);
        txtCommunityCity.setVisible(true);
        btnAddCommunity.setVisible(true);
    }//GEN-LAST:event_btnCreateCommunityActionPerformed

    private void btnAddCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommunityActionPerformed
        // TODO add your handling code here:
        try{
            commName = txtCommunityName.getText();
            commCity = txtCommunityCity.getText();
            if(communityValidation()){
                Community c = comd.addNewCommunity(commName);
                c.setName(commName);
                c.setCity(commCity);
                initialSetup();
                JOptionPane.showMessageDialog(this, "Community added");
                populateCommunities();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter all values and try again");
        }
    }//GEN-LAST:event_btnAddCommunityActionPerformed

    private void btnViewCommunitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCommunitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCommunitiesActionPerformed

    private void btnUpdateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCommunityActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCommunities.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a community to view its details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCommunities.getModel();
        Community c= (Community) model.getValueAt(selectedRowIndex, 0);
        try{
            commName = txtCommunityName.getText();
            commCity = txtCommunityCity.getText();
            if(communityValidation()){
                c.setName(commName);
                c.setCity(commCity);
                initialSetup();
                JOptionPane.showMessageDialog(this, "Community updated");
                populateCommunities();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter all values and try again");
        }
    }//GEN-LAST:event_btnUpdateCommunityActionPerformed

    private void btnViewUpdateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateCommunityActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCommunities.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a community to view their details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCommunities.getModel();
        Community c= (Community) model.getValueAt(selectedRowIndex, 0);
        
        lblCommunityName.setVisible(true);
        txtCommunityName.setVisible(true);
        lblCommunityCity.setVisible(true);
        txtCommunityCity.setVisible(true);
        btnUpdateCommunity.setVisible(true);
        
        txtCommunityName.setText(c.getName());
        txtCommunityCity.setText(c.getCity());
    }//GEN-LAST:event_btnViewUpdateCommunityActionPerformed

    private void txtCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityNameActionPerformed

    private void txtCommunityCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityCityActionPerformed

    private void btnUpdateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHouseActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblHouses.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a house to view their details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
        House h= (House) model.getValueAt(selectedRowIndex, 0);
        
        try{
            houseName = txtHouseName.getText();
            houseComm = txtHouseCommunity.getText();
            houseCity = txtHouseCity.getText();
            if(houseValidation()){
                h.setName(houseName);
                h.setCommunity(houseComm);
                h.setCity(houseCity);
                initialSetup();
                JOptionPane.showMessageDialog(this, "House updated");
                populateHouses();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter all values and try again");
        }
    }//GEN-LAST:event_btnUpdateHouseActionPerformed

    private void btnViewUpdateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateHouseActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblHouses.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a house to view their details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
        House h= (House) model.getValueAt(selectedRowIndex, 0);
        
        lblHouseName.setVisible(true);
        txtHouseName.setVisible(true);
        lblHouseCommunity.setVisible(true);
        txtHouseCommunity.setVisible(true);
        lblHouseCity.setVisible(true);
        txtHouseCity.setVisible(true);
        btnUpdateHouse.setVisible(true);
        
        txtHouseName.setText(h.getName());
        txtHouseCommunity.setText(h.getCommunity());
        txtHouseCity.setText(h.getCity());
    }//GEN-LAST:event_btnViewUpdateHouseActionPerformed

    private void txtHouseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouseNameActionPerformed

    private void txtHouseCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouseCommunityActionPerformed

    private void btnCreateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHouseActionPerformed
        // TODO add your handling code here:
        lblHouseName.setVisible(true);
        txtHouseName.setVisible(true);
        lblHouseCommunity.setVisible(true);
        txtHouseCommunity.setVisible(true);
        lblHouseCity.setVisible(true);
        txtHouseCity.setVisible(true);
        btnAddHouse.setVisible(true);
    }//GEN-LAST:event_btnCreateHouseActionPerformed

    private void btnAddHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHouseActionPerformed
        // TODO add your handling code here:
        try{
            houseName = txtHouseName.getText();
            houseComm = txtHouseCommunity.getText();
            houseCity = txtHouseCity.getText();
            if(houseValidation()){
                House h = hod.addNewHouse();
                h.setName(houseName);
                h.setCommunity(houseComm);
                h.setCity(houseCity);
                initialSetup();
                JOptionPane.showMessageDialog(this, "House added");
                populateHouses();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter all values and try again");
        }
        
    }//GEN-LAST:event_btnAddHouseActionPerformed

    private void btnViewHousesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHousesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewHousesActionPerformed

    private void txtHouseCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouseCityActionPerformed

    public void populateCities(){
        DefaultTableModel model = (DefaultTableModel) tblCities.getModel();
         model.setRowCount(0);
         for(City c : cd.getCityDirectory()){
               Object row[] = new Object[1];
               row[0] = c;
               model.addRow(row); 
        }
    }
    
    public void populateCommunities(){
        DefaultTableModel model = (DefaultTableModel) tblCommunities.getModel();
         model.setRowCount(0);
         for(Community c : comd.getCommunityDirectory()){
               Object row[] = new Object[1];
               row[0] = c;
               model.addRow(row); 
        }
    }
    
    public void populateHouses(){
        DefaultTableModel model = (DefaultTableModel) tblHouses.getModel();
         model.setRowCount(0);
         for(House h : hod.getHouseDirectory()){
               Object row[] = new Object[1];
               row[0] = h;
               model.addRow(row); 
        }
    }
    
    public Boolean cityValidation(){
            ArrayList message = null;
            message = new ArrayList(0);
            if (cityName.isBlank() || !(cityName.matches("^[ a-zA-Z1-9]*$"))){
                message.add("Name cannot be blank or contain special characters. Please enter a valid name and try again");
            }
            if(!(message.isEmpty())){
            JOptionPane.showMessageDialog(this, message.toArray());
            message.clear();
            return false;
            }
            else{
                return true;
            }
        } 
    
    public Boolean communityValidation(){
            ArrayList message = null;
            message = new ArrayList(0);
            if (commName.isBlank() || !(commName.matches("^[ a-zA-Z1-9]*$"))){
                message.add("Name cannot be blank or contain special characters. Please enter a valid name and try again");
            }
            if(cd.isACity(commCity) == false){
                message.add("City name does not match with present records. Please enter a valid name and try again");
            }
            if(!(message.isEmpty())){
            JOptionPane.showMessageDialog(this, message.toArray());
            message.clear();
            return false;
            }
            else{
                return true;
            }
        } 
    
    public Boolean houseValidation(){
            ArrayList message = null;
            message = new ArrayList(0);
            if (houseName.isBlank() || !(houseName.matches("^[ a-zA-Z1-9]*$"))){
                message.add("Name cannot be blank or contain special characters. Please enter a valid name and try again");
            }
            if(comd.isACommunity(houseComm) == false){
                message.add("Community name does not match with present records. Please enter a valid name and try again");
            }
            if(cd.isACity(houseCity) == false){
                message.add("City name does not match with present records. Please enter a valid name and try again");
            }
            if(!(message.isEmpty())){
            JOptionPane.showMessageDialog(this, message.toArray());
            message.clear();
            return false;
            }
            else{
                return true;
            }
        } 
    
    public void initialSetup(){
        lblCityName.setVisible(false);
        txtCityName.setVisible(false);
        btnAddCity.setVisible(false);
        btnUpdateCity.setVisible(false);
        
        lblCommunityName.setVisible(false);
        txtCommunityName.setVisible(false);
        lblCommunityCity.setVisible(false);
        txtCommunityCity.setVisible(false);
        btnAddCommunity.setVisible(false);
        btnUpdateCommunity.setVisible(false);
        
        lblHouseName.setVisible(false);
        txtHouseName.setVisible(false);
        lblHouseCommunity.setVisible(false);
        txtHouseCommunity.setVisible(false);
        lblHouseCity.setVisible(false);
        txtHouseCity.setVisible(false);
        btnAddHouse.setVisible(false);
        btnUpdateHouse.setVisible(false);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCity;
    private javax.swing.JButton btnAddCommunity;
    private javax.swing.JButton btnAddHouse;
    private javax.swing.JButton btnCreateCommunity;
    private javax.swing.JButton btnCreateHouse;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnUpdateCity;
    private javax.swing.JButton btnUpdateCommunity;
    private javax.swing.JButton btnUpdateHouse;
    private javax.swing.JButton btnViewCities;
    private javax.swing.JButton btnViewCommunities;
    private javax.swing.JButton btnViewHouses;
    private javax.swing.JButton btnViewUpdateCity;
    private javax.swing.JButton btnViewUpdateCommunity;
    private javax.swing.JButton btnViewUpdateHouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCommunityCity;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JLabel lblHouseCity;
    private javax.swing.JLabel lblHouseCommunity;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JTable tblCities;
    private javax.swing.JTable tblCommunities;
    private javax.swing.JTable tblHouses;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtCommunityCity;
    private javax.swing.JTextField txtCommunityName;
    private javax.swing.JTextField txtHouseCity;
    private javax.swing.JTextField txtHouseCommunity;
    private javax.swing.JTextField txtHouseName;
    // End of variables declaration//GEN-END:variables
}
