/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.CityDirectory;
import model.CommunityAdmin;
import model.CommunityAdminDirectory;
import model.CommunityDirectory;
import model.Doctor;
import model.DoctorDirectory;
import model.Encounter;
import model.EncounterHistory;
import model.HospitalAdmin;
import model.HospitalAdminDirectory;
import model.HospitalDirectory;
import model.HouseDirectory;
import model.Patient;
import model.PatientDirectory;
import model.SystemAdmin;
import model.SystemAdminDirectory;
import model.VitalSignsHistory;

/**
 *
 * @author mohit
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    String role;
    String emailId;
    String password;
    PatientDirectory pd;
    DoctorDirectory dd;
    JSplitPane sp;
    EncounterHistory eh;
    VitalSignsHistory vsh;
    SystemAdminDirectory sad;
    HospitalDirectory hd;
    CommunityAdminDirectory cad;
    CityDirectory cd;
    CommunityDirectory comd;
    HouseDirectory hod;
    HospitalAdminDirectory had;
    
    public LoginJPanel(PatientDirectory pd, DoctorDirectory dd, JSplitPane sp, EncounterHistory eh, VitalSignsHistory vsh, SystemAdminDirectory sad, HospitalDirectory hd, 
            CommunityAdminDirectory cad, CityDirectory cd, CommunityDirectory comd, HouseDirectory hod, HospitalAdminDirectory had) {
        initComponents();
        this.pd = pd;
        this.dd = dd;
        this.sp = sp;
        this.eh = eh;
        this.vsh = vsh;
        this.sad = sad;
        this.hd = hd;
        this.hod = hod;
        
        this.cad = cad;
        this.cd = cd;
        this.comd = comd;
        
        this.had = had;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Phosphate", 0, 36)); // NOI18N
        lblLogin.setText("Login");
        add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 77, -1, -1));

        lblEmailId.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblEmailId.setText("Email ID:");
        add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 210, -1, -1));

        lblPassword.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 245, -1, -1));
        add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 207, 175, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 242, 175, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select a Role", "System Admin", "Hospital Admin", "Community Admin", "Patient", "Doctor" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 166, -1, -1));

        lblRole.setFont(new java.awt.Font("Krungthep", 0, 13)); // NOI18N
        lblRole.setText("User role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 169, -1, -1));

        btnLogin.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 308, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/mohit/Desktop/INFO5100 (14259) Application Engineering and Development /Rayalacheruvu_Maruti_002109594/Assignment2_HospitalCRUD/images/login.png")); // NOI18N
        jLabel1.setText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        role = jComboBox1.getSelectedItem().toString();
        emailId = txtEmailId.getText();
        password = String.valueOf(txtPassword.getPassword());
        
        if(loginValidation()){
            if("Patient".equals(role)){
                if(pd.validateLogin(emailId, password)){
                    Patient p = pd.getPatient(emailId, password);
                    JOptionPane.showMessageDialog(this, "Signed in Successfully");
                    PatientViewJPanel patientView = new PatientViewJPanel(dd, pd, p, eh, vsh);
                       sp.setRightComponent(patientView);
                }
                else
                    JOptionPane.showMessageDialog(this, "Sign in Failed");
            }
            else if("Doctor".equals(role)){
                if(dd.validateLogin(emailId, password)){
                    Doctor d = dd.getDoctor(emailId, password);
                    JOptionPane.showMessageDialog(this, "Signed in Successfully");
                    DoctorViewJPanel doctorView = new DoctorViewJPanel(d, eh, vsh);
                       sp.setRightComponent(doctorView);
                }
                else
                    JOptionPane.showMessageDialog(this, "Sign in Failed");
            }
            else if("System Admin".equals(role)){
                if(sad.validateLogin(emailId, password)){
                    SystemAdmin sa = sad.getSystemAdmin(emailId, password);
                    JOptionPane.showMessageDialog(this, "Signed in Successfully");
                    SystemAdminJPanel systemAdminView = new SystemAdminJPanel(pd, dd, eh, vsh, sp, hd);
                       sp.setRightComponent(systemAdminView);
                }
                else
                    JOptionPane.showMessageDialog(this, "Sign in Failed");
            }
            else if("Hospital Admin".equals(role)){
                if(had.validateLogin(emailId, password)){
                    HospitalAdmin ha = had.getHospitalAdmin(emailId, password);
                    JOptionPane.showMessageDialog(this, "Signed in Successfully");
                    HospitalAdminJPanel hospitalAdminView = new HospitalAdminJPanel(pd, dd, eh, vsh, sp, hd);
                       sp.setRightComponent(hospitalAdminView);
                }
                else
                    JOptionPane.showMessageDialog(this, "Sign in Failed");
            }
            else if("Community Admin".equals(role)){
                if(cad.validateLogin(emailId, password)){
                    CommunityAdmin ca = cad.getCommunityAdmin(emailId, password);
                    JOptionPane.showMessageDialog(this, "Signed in Successfully");
                    CommunityAdminJPanel communityAdminView = new CommunityAdminJPanel(sp, cd, comd, hod);
                       sp.setRightComponent(communityAdminView);
                }
                else
                    JOptionPane.showMessageDialog(this, "Sign in Failed");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

        private Boolean loginValidation(){
            ArrayList message = null;
            message = new ArrayList(0);
            if("Please Select a Role".equals(role)){
                message.add("Please select a role and try again");
            }
            if(emailId.isBlank()){
                message.add("Please enter Email ID and try again");
            }
            if(password.isBlank()){
                message.add("Please enter password and try again");
            }
            if(!(message.isEmpty())){
            JOptionPane.showMessageDialog(this, message.toArray());
            message.clear();
            return false;
            }
            else{
                return true;
            }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
