/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JSplitPane;
import model.CityDirectory;
import model.CommunityAdmin;
import model.CommunityAdminDirectory;
import model.CommunityDirectory;
import model.Doctor;
import model.DoctorDirectory;
import model.Encounter;
import model.EncounterHistory;
import model.HospitalAdmin;
import model.HospitalAdminDirectory;
import model.HospitalDirectory;
import model.HouseDirectory;
import model.Patient;
import model.PatientDirectory;
import model.SystemAdmin;
import model.SystemAdminDirectory;
import model.VitalSignsHistory;

/**
 *
 * @author mohit
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    PatientDirectory pd;
    DoctorDirectory dd;
    EncounterHistory eh;
    VitalSignsHistory vsh;
    SystemAdminDirectory sad;
    
    HospitalDirectory hd;
    CommunityAdminDirectory cad;
    CityDirectory cd;
    CommunityDirectory comd;
    HouseDirectory hod;
    
    HospitalAdminDirectory had;
    
    JSplitPane sp;
    
    public MainJFrame() {
        initComponents();
        pd = new PatientDirectory();
        dd = new DoctorDirectory();
        eh = new EncounterHistory();
        vsh = new VitalSignsHistory();
        sad = new SystemAdminDirectory();
        hd = new HospitalDirectory();
        
        cad = new CommunityAdminDirectory();
        cd = new CityDirectory();
        comd = new CommunityDirectory();
        hod = new HouseDirectory();
        
        had = new HospitalAdminDirectory();
        
        sp = new JSplitPane();
        
        dummyData();
        
        ImageIcon icon = new ImageIcon("/Users/mohit/Desktop/INFO5100 (14259) Application Engineering and Development /Rayalacheruvu_Maruti_002109594/Assignment2_HospitalCRUD/images/home.jpg");
        Image image = icon.getImage().getScaledInstance(lblPhoto.getHeight(), lblPhoto.getWidth(), Image.SCALE_SMOOTH);
        lblPhoto.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnSignup = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        lblContinue = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(btnSignup)
                .addGap(72, 72, 72)
                .addComponent(btnLogin)
                .addContainerGap(926, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 255));

        lblContinue.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 24)); // NOI18N
        lblContinue.setText("Click Sign Up or Login to Continue");

        lblWelcome.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 36)); // NOI18N
        lblWelcome.setText("WELCOME TO HOSPITAL MANAGEMENT SYSTEM");

        lblPhoto.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(33, 33, 33))
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(lblContinue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContinue)
                .addGap(68, 68, 68)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        SignupJPanel signUpPanel = new SignupJPanel(pd, dd);
        splitPane.setRightComponent(signUpPanel);
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        LoginJPanel loginPanel = new LoginJPanel(pd, dd,splitPane, eh, vsh, sad, hd, cad, cd, comd, hod, had);
        splitPane.setRightComponent(loginPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    public void dummyData(){
        Patient p = pd.addNewPatient();
        p.setName("Bob Marley");
        p.setEmailId("bob");
        p.setDob(new Date(01/01/1999));
        p.setAge(25);
        p.setGender("Male");
        p.setPhNo("1234567890");
        p.setPassword("bob");
        p.setHeight(123);
        p.setWeight(123);
        p.setCity("Boston");
        
        Patient p1 = pd.addNewPatient();
        p1.setName("Mohit Marley");
        p1.setEmailId("mohit");
        p1.setDob(new Date(01/01/1999));
        p1.setAge(25);
        p1.setGender("Male");
        p1.setPhNo("1234567890");
        p1.setPassword("mohit");
        p1.setHeight(123);
        p1.setWeight(123);
        p1.setCity("Boston");
        
        Doctor d = dd.addNewDoctor();
        d.setName("Job Marley");
        d.setEmailId("job");
        d.setDob(new Date(01/01/1999));
        d.setAge(25);
        d.setGender("Male");
        d.setPhNo("1234567890");
        d.setPassword("job");
        d.setSpeciality("Heart");
        d.setYearsOfExp(1);
        d.setHospital("Hospital");
        d.setArea("LMA");
        
        Encounter e = eh.addNewEncounter();
        e.setPatientName("Bob Marley");
        e.setDoctorName("Job Marley");
        e.setDate(new Date(01/01/1999));
        
        SystemAdmin s = sad.addNewSystemAdmin();
        s.setEmailId("sys");
        s.setPassword("sys");
        
        CommunityAdmin ca = cad.addNewCommunityAdmin();
        ca.setEmailId("com");
        ca.setPassword("com");
        
        HospitalAdmin ha = had.addNewHospitalAdmin();
        ha.setEmailId("hos");
        ha.setPassword("hos");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblContinue;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
